// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3hdd4umnFklW_LK9TQc96qnScYLSzv0k',
    appId: '1:315330564655:web:7fd3f0f6abfb8dc2616cda',
    messagingSenderId: '315330564655',
    projectId: 'math-wis',
    authDomain: 'math-wis.firebaseapp.com',
    databaseURL: 'https://math-wis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'math-wis.appspot.com',
    measurementId: 'G-282LYFVFSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFqDPpbd6C-qEoksKBwhKy06k51i5Vq4E',
    appId: '1:315330564655:android:62bbc8ffc58cd3f2616cda',
    messagingSenderId: '315330564655',
    projectId: 'math-wis',
    databaseURL: 'https://math-wis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'math-wis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuZLzCcWl0sMzQHVlj1Aba7ymlTWtukSw',
    appId: '1:315330564655:ios:4865c02ef9a847fa616cda',
    messagingSenderId: '315330564655',
    projectId: 'math-wis',
    databaseURL: 'https://math-wis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'math-wis.appspot.com',
    androidClientId: '315330564655-aca692d3t1396qv2j7fipdbdfp3lhbjh.apps.googleusercontent.com',
    iosClientId: '315330564655-8gal5fct8rm9otk2pgq4pdjmtbfne3ju.apps.googleusercontent.com',
    iosBundleId: 'net.kincode.maths',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuZLzCcWl0sMzQHVlj1Aba7ymlTWtukSw',
    appId: '1:315330564655:ios:4865c02ef9a847fa616cda',
    messagingSenderId: '315330564655',
    projectId: 'math-wis',
    databaseURL: 'https://math-wis-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'math-wis.appspot.com',
    androidClientId: '315330564655-aca692d3t1396qv2j7fipdbdfp3lhbjh.apps.googleusercontent.com',
    iosClientId: '315330564655-8gal5fct8rm9otk2pgq4pdjmtbfne3ju.apps.googleusercontent.com',
    iosBundleId: 'net.kincode.maths',
  );
}
