name: Flutter CI APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


defaults:
  run:
    working-directory: maths

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: pr-mpt/actions-commit-hash@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: ncipollo/release-action@v1
        with:
          artifacts: maths/build/app/outputs/flutter-apk/app-debug.apk
          tag: ${{ steps.vars.outputs.sha_short }}
